import sys
import os
from pathlib import Path
from unittest.mock import patch

# Add project root to Python path
project_root = Path(__file__).parent.parent
sys.path.append(str(project_root))

from src.core.engine import HybridEngine

def test_real_llm_logic():
    print("=== Explainability Verification (Real LLM / Mock DB) ===")
    
    # 1. Check API Key
    if not os.environ.get("GOOGLE_API_KEY"):
        print("❌ GOOGLE_API_KEY not found. Cannot run real LLM test.")
        return

    engine = HybridEngine()

    # We ONLY mock the storage layer (VectorStore & Database)
    # ensuring we have "books" to recommend regardless of local DB state.
    # We DO NOT mock 'parse_query' or 'explainer', so we test the REAL AI logic.
    
    with patch.object(engine.vs, 'search') as mock_vs_search, \
         patch.object(engine.db, 'get_item') as mock_db_get:
         
        # --- Mock Data Setup ---
        # Simulate Qdrant returning 3 hits
        mock_vs_search.return_value = [
            {"id": 101, "score": 0.85},
            {"id": 102, "score": 0.82},
            {"id": 103, "score": 0.75}
        ]
        
        # Simulate Database returning book details
        # We make up some content for the LLM to read.
        def get_dummy_book(eid):
            books = {
                101: {
                    "id": 101, "name": "The Azure Sky", "author": "Celine", 
                    "classification": "Romance", "tags": ["magic", "school"],
                    "intro": "A story about a girl who discovers she can control the blue sky magic."
                },
                102: {
                    "id": 102, "name": "Crimson Blade", "author": "Warrior X", 
                    "classification": "Fantasy", "tags": ["war", "blood"],
                    "intro": "He wields a sword made of blood. A dark fantasy epic."
                },
                103: {
                    "id": 103, "name": "Silent Forest", "author": "Druid", 
                    "classification": "Mystery", "tags": ["nature", "spirits"],
                    "intro": "The trees whisper secrets of the past. A mystery set in an ancient forest."
                }
            }
            return books.get(eid)
        
        mock_db_get.side_effect = get_dummy_book
        # -----------------------

        query = "fantasy novels with magic"
        print(f"\nQUERY: '{query}'")
        print("1. Calling Real `parse_query` (Gemini)...")
        
        try:
            # THIS CALLS THE REAL ENGINE logic
            result = engine.search(query, limit=5)
            
            print("\n✅ Search Completed.")
            print(f"Original Query: {result['query']}")
            
            print("\n--- Parsed Criteria (Generated by Gemini) ---")
            for c in result['parsed_criteria']:
                print(f"- {c['name']} (w={c['weight']}): {c.get('parameters')}")
            
            print("\n--- Results Explanation (Generated by Gemini) ---")
            for i, res in enumerate(result['results']):
                item = res['item']
                print(f"\n[Rank {i+1}] {item['name']} (Score: {res['score']:.2f})")
                
                explanation = res.get('explanation')
                if explanation:
                    print(f"📝 Explanation:\n{explanation}")
                else:
                    print("No explanation generated.")

        except Exception as e:
            print(f"\n❌ Error during execution: {e}")
            import traceback
            traceback.print_exc()

if __name__ == "__main__":
    test_real_llm_logic()
